version: "3.9"

services:

  # Conteneur 1 : MongoDB
  mongodb:
    image: mongo:7.0
    container_name: medical_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Les données sont conservées même si le conteneur est supprimé
    networks:
      - medical_network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Conteneur 2 : Script de migration Python
  migration:
    build: .
    container_name: medical_migration
    depends_on:
      mongodb:
        condition: service_healthy  # Attend que MongoDB soit prêt
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB: medical_db
      MONGO_COLLECTION: patients
      CSV_PATH: /data/medical_data.csv 
    volumes:
      - ./data:/data  # Le dossier local ./data est monté directement dans le conteneur
    networks:
      - medical_network
    restart: "no"  # Le conteneur s'arrête une fois la migration terminée

volumes:
  mongo_data:  # Stockage persistant des données MongoDB

networks:
  medical_network:  # Réseau privé entre les deux conteneurs
    driver: bridge